### ISSUE TITLE
How long does it take to get refunded after a cancellation ?

### ISSUE THREAD

**Issue by zaibon** [threefoldfoundation/tfta-trader#15]

**Comment by waleedhammam** [comment]
Implemented cancelling algorithms, Still testing the whole scenarios.

Will be merged to production after finishing: https://github.com/threefoldfoundation/tfta-trader/issues/17

**Comment by zaibon** [comment]
So if I understand correctly, today there is no refund at all when cancelling an offer ?
Am I correct to assume that any offer that was cancelled before this is implement will still be refunded properly ?

**Comment by waleedhammam** [comment]
Yes a proper refund will happen, we are handling these cases.

**Comment by waleedhammam** [comment]
Code merged to production, refund done
![Screenshot from 2020-07-16 11-28-12](https://user-images.githubusercontent.com/10658229/87654848-c33f2900-c757-11ea-9fc8-4c494fa84a85.png)

**Comment by zaibon** [comment]
indeed, thanks
