### ISSUE TITLE
distribution of the sold XLM

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfta-trader#17]

**Comment by ranatrk** [comment]
WIP on branch https://github.com/threefoldfoundation/tfta-trader/tree/development_distrib : 

**Progress:**
- creating orders
- distribution when the current 1000 TFT is sold

**TODO:**
- merge bot with tft issuer with distribution service
- testing

**Comment by robvanmieghem** [comment]
@ranatrk the tft_issuer is an  dependent service  that only needs the selling service account as a startup parameter  to run

**Comment by ranatrk** [comment]
Progress: 
- Adding cancellation scenarios
- Updated distibution service
https://github.com/threefoldfoundation/tfta-trader/commit/564d32b07bdf6592a8a364b7794b890e8d6afc4e
https://github.com/threefoldfoundation/tfta-trader/commit/9607a25f6a2f221f2730f49dbf997451a7e58a35

TODO: after fixing/resolving issues mentioned below, detailed testing needs to be done

currently **blocked** on stellar, where we get multiple errors with error operation `op_underfunded`:
- when creating a transfer (manually with stellar client or with 3bot staging application) with enough(extra) funds (sometimes it works and sometimes not having the same balance and transfer amount)
![image](https://user-images.githubusercontent.com/17128393/87070316-e712e400-c218-11ea-8cc9-657f21df818c.png)

- when creating selling order on stellar testnet with enough funds, (tried with selling 50TFT,100TFT,999TFT,1000TFT)
- selling order only worked once with 10, and no XLMs were returned
- on https://testnet.interstellar.exchange/, when we tried selling XLMs to get TFTs as usual, success message shown but no TFTs transferred to the wallet : https://horizon-testnet.stellar.org/transactions/f98126dcebd67e97f62fac321c75ffac081eab6117dea56578ed3990d45543b3/operations

**looking into previous issues  to know if it is from stellar itself or not**

**Comment by ranatrk** [comment]
cancellation & distribution scenario additions: 
https://github.com/threefoldfoundation/tfta-trader/commit/e35b7457e840cffb2a6da7b9ec4d336caceaa22d
https://github.com/threefoldfoundation/tfta-trader/commit/278394a86ec5bad3215cd0c77248e21dfa93a385
https://github.com/threefoldfoundation/tfta-trader/commit/50a6aff27ac7a8b66ca5fc0d4422a9f7d0e553d7

docs:
 https://github.com/threefoldfoundation/tfta-trader/blob/7d082930ef8c485517675d5803ea00c1909cd423/docs/tfta_sales_package.md

Tested scenarios of distribution and cancellation without tft issuer(manually transfer TFTs and XLMs)
TODO: Test scenarios again for smooth flow with tft issuer and setup similar to production
