### ISSUE TITLE
No need to ask if the decentralization poll has been filled in if there are open orders

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfta-trader#19]
![Screenshot 2020-07-14 at 08 07 06](https://user-images.githubusercontent.com/3511318/87390760-c7c5df00-c5a9-11ea-92db-ae2140f843f0.png)

Actually, we can already check if it is filled in so this question is not needed at all

**Comment by waleedhammam** [comment]
added in https://github.com/threefoldfoundation/tfta-trader/commit/69d5b9d2df9c8e9171ea18b1ac9976a767035f4f

Main screen
![Screenshot from 2020-07-14 10-54-21](https://user-images.githubusercontent.com/10658229/87406426-fe5b2400-c5c0-11ea-8e75-153ed6f81532.png)

next when not answering the poll
![Screenshot from 2020-07-14 10-54-26](https://user-images.githubusercontent.com/10658229/87406463-087d2280-c5c1-11ea-8abe-b83150aec7b2.png)


next when answering the poll
![Screenshot from 2020-07-14 10-56-56](https://user-images.githubusercontent.com/10658229/87406494-12068a80-c5c1-11ea-87af-1cba6dfadb61.png)
