### ISSUE TITLE
Change the title to "TFTA selling Bot"

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfta-trader#20]
![Screenshot 2020-07-14 at 08 17 54](https://user-images.githubusercontent.com/3511318/87391216-9d285600-c5aa-11ea-9619-3553ddad0702.png)

**Comment by waleedhammam** [comment]
added in https://github.com/threefoldfoundation/tfta-trader/commit/c2a37adf576188608a625ff2c5581480e23032bb

![Screenshot from 2020-07-14 10-45-23](https://user-images.githubusercontent.com/10658229/87405169-58f38080-c5bf-11ea-96c6-8627d19f276e.png)
