### ISSUE TITLE
Modify the open order overview a bit

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfta-trader#21]
![Screenshot 2020-07-14 at 08 08 55](https://user-images.githubusercontent.com/3511318/87391285-c0530580-c5aa-11ea-9f9d-73cee332b49e.png)

Please:
- modify the "stellaraddress" label to "address"
- drop the "_" in all  labels
- show the payment received in a human readable datetime instead of in epoch
- change "wanted_asset" label to "asset to receive"
- change "distribution_address" to "receiving address"
- hide the distribution_ongoing, cancelled and refund_transaction_id fields
If the receiving address is empty, show the stellar address

**Comment by waleedhammam** [comment]
fixed in: https://github.com/threefoldfoundation/tfta-trader/commit/118f4c6ad527a8d17e1dbc3910d5994748f57dbf

![Screenshot from 2020-07-14 11-27-14](https://user-images.githubusercontent.com/10658229/87409315-0fa62f80-c5c5-11ea-8b5e-1a23b8bd846c.png)
