### ISSUE TITLE
bring the 1.0 version in production

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfta-trader#23]
- [x] fund the trading wallet with 1000 XLM and 1000TFT
- [x] Update the code
- [x] run the cancellation service
- [x] verify
- [x] run the distribution service
- [x] run the tft issuer

**Comment by waleedhammam** [comment]
Updated and waiting for selling
![Screenshot from 2020-07-16 11-30-04](https://user-images.githubusercontent.com/10658229/87655027-fbdf0280-c757-11ea-8807-f489782c4cf6.png)
