### ISSUE TITLE
Modify validate payment error message

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfta-trader#8]
![2020-07-02 12 10 51](https://user-images.githubusercontent.com/3511318/86346393-23fd3a80-bc5d-11ea-9bd3-09655d275eda.jpg)

Change to : Wrong amount of TFTA's has been received, they have been sent back to your wallet
Also, the amount is shown as TFT instead of TFTA ?

**Comment by ranatrk** [comment]
The TFT is just for testing, when complete will be updated with the correct currency (TFTA) and asset in a variable used across the whole chatflow

**Comment by ranatrk** [comment]
change error message: https://github.com/threefoldfoundation/tfta-trader/commit/90d8757c1ba5ba57799d517cc4d95a3cf1ab112a
